apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: sesaquecruz/lab-2-database:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
              name: database
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DATABASE_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DATABASE_PASSWORD
          volumeMounts:
            - name: database-pvc
              mountPath: /var/lib/postgresql/data/
      volumes:
        - name: database-pvc
          persistentVolumeClaim:
            claimName: database-pvc