apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  labels:
    type: database-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /database-data/