server:
  port: 80
  servlet:
    context-path: "/"

spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://database-connection/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect